### ISSUE TITLE
How to build without qtcreator?

### ISSUE THREAD

**Issue by oz123** [gcompris/GCompris-qt#185]
Hi, 
I was wonder if you can document how to build this software with CLI only.
It seems to me odd that I need to build qtcreator just to build this software. Is there no way to export this to a normal CMAKE work flow?

**Comment by petitlapin** [comment]
Hi,

You can follow http://gcompris.net/wiki/Qt_Quick_development_process#Compilation to compile it and run it on command line.

Johnny

**Comment by petitlapin** [comment]
Please reopen the project or contact us in gcompris-devel@kde.org if you need more info
