### ISSUE TITLE
Clickgame: sometimes fishes misbehave

### ISSUE THREAD

**Issue by axredneck** [gcompris/GCompris-qt#186]
Sometimes fish doesn't turh around when it approaches right side of screen, then it swims backward to left, and when it approaches left side of screen it stops moving along X axis and begins to sink until it hides behind "Menu" button and becomes unreachable.
Unfortunately i didn't see this mistake in src/activities/clickgame/Fish.qml at first sight.

**Comment by petitlapin** [comment]
Hi, I just managed to reproduce, I'll take a bigger look to understand.
Thank you for reporting,

Johnny

**Comment by petitlapin** [comment]
I commited a fix in https://github.com/gcompris/GCompris-qt/commit/f515d3543257db65f7a5f1d4c4ecfc41416be808 
The issue was when setting the x value at creation. For the "bad" fishes, it was set to 0 and causing issue. Can you check if it's good for you?

Thank you for reporting the bug,
Johnny

**Comment by axredneck** [comment]
Thank You!
Now my nieces will have fun clicking fishes.
