### ISSUE TITLE
"make install" does not install desktop file nor icons

### ISSUE THREAD

**Issue by probonopd** [gcompris/GCompris-qt#192]
`make install` does not install the desktop file in `/usr/share/applications/` nor the icons in `/usr/share/icons/...`.

Build log:
https://travis-ci.org/probonopd/GCompris-qt/builds/259858983#L2346-L2498

**Comment by petitlapin** [comment]
Hi,

I did a fix in https://cgit.kde.org/gcompris.git/commit/?id=4ffffaf04ee775bf175bb451cd4796c4d949766b
If you install from git, you need to have ECM with version at least 1.6.0 to have the icon and desktop file installed. Can you check if you have this version (I added a log during the configuration phase)?

Johnny

**Comment by probonopd** [comment]
Thanks @petitlapin. As I am building on Travis CI on Ubuntu 14.04, it seems like extra-cmake-modules is not available there. Why is it needed to just do a simple "copy" operation that I can do in two lines in bash? Sure I could compile it myself, but wouldn't that be overkill? https://askubuntu.com/a/859867

**Comment by petitlapin** [comment]
The ECM provides a portable way to get the different folder where to put the files. I guess we can do without it and add the copy in the script and once the CI will have the ECM we can remove the manual copy?

**Comment by probonopd** [comment]
I am copying in the 2 files manually for now. Less hassle than ECM.
