### ISSUE TITLE
text is not displayed in the program

### ISSUE THREAD

**Issue by cr6git** [gcompris/GCompris-qt#193]
Hello, 
I am maintainer for [Void](https://github.com/voidlinux) linux (the best distro IMO) and I want to create a package. 
I can compile `gcompris-qt` from source and run the program. 

BUT: the text is not displayed, as you can see in my three screenshots. 
[Screenshot-01](https://prnt.sc/g7wwf9) 
[Screenshot-02](https://prnt.sc/g7wwsc) 
[Screenshot-03](https://prnt.sc/g7wx2p) 

This is weird ! 
I also noticed this message when launching the program: 
`OpenType support missing for script 11`

Is there a problem with the fonts ? 
I hope you can help me. 

Regards.

**Comment by petitlapin** [comment]
Hi,
this is the first time we have this issue of missing texts, we are taking a look.
Thank you for the report,
Johnny

**Comment by petitlapin** [comment]
Hi,
I also have the error in my archlinux but texts are well displayed.
I installed a void linux (lxde) in a vm and compiled gcompris and I have the texts.
Do you have some specific configuration?

**Comment by cr6git** [comment]
No, no specific configuration... 
Well, I am truly sorry that I cannot create a package for Void :(

**Comment by petitlapin** [comment]
Which DE do you use and which locale is your computer?
On my side, I tried putting a non existing font to check if it could come from it but there is a default one.
I found this bug: https://bugreports.qt.io/browse/QTBUG-32729 but it should be fixed and we don't use the NativeMode.

**Comment by cr6git** [comment]
Hi @petitlapin 
Today, I made a new attempt at creating a package for Void linux. 
It works perfectly, the issue is fixed ! 😅 
See [#9551](https://github.com/voidlinux/void-packages/pull/9551) 

Regards.

**Comment by petitlapin** [comment]
Hi,

good news :).

I'm not sure how packaging works for Void linux, but it would be better to use the source code from http://gcompris.net/download/qt/src/ because it also contains the translations.

Johnny

**Comment by cr6git** [comment]
Thanks for the advice, I will look at it.

**Comment by cr6git** [comment]
Done.
