### ISSUE TITLE
No time delay in memory(-tux) in user's turn after second card

### ISSUE THREAD

**Issue by solarjoe** [gcompris/GCompris-qt#211]
Hello,

when playing memory(-tux), there is no time delay after the user rotated the second card. Immediately after the second card has been flipped Tux starts or, in case of single player, the next round starts.

The time delay should be about as long as between Tux' second card and the user's next round.

**Comment by petitlapin** [comment]
Fixed in https://cgit.kde.org/gcompris.git/commit/?id=86d92420db9bb0764fb55bdea57726142ded0f42, I set 1500 ms as much as when Tux turns its second card.

Thank you!
