### ISSUE TITLE
No light in Tux's  house in renewable_energy

### ISSUE THREAD

**Issue by solarjoe** [gcompris/GCompris-qt#212]

**Comment by solarjoe** [comment]
The village's and the citie's windows are illuminated it the switch is flipped, Tux's house stays dark.
Kids notice the details :)

**Comment by petitlapin** [comment]
Thank you for reporting the issues. We plan to do a release soon so we'll fix them in it.
Don't hesitate if there are more issues like this one, it's by polishing details that the software will be greater :)

**Comment by petitlapin** [comment]
Fixed in https://phabricator.kde.org/R2:c68bfd76203fa7f374f785cf70cc46e9ef39e5f4
Thank you for reporting,
Johnny
