### ISSUE TITLE
Translation fix

### ISSUE THREAD

**Issue by solarjoe** [gcompris/GCompris-qt#214]
In the German version of the current version the checkers and checkers_2players are listed as chess. The correct name is "Dame".

Can I add small fixes on the translation like this one somewhere in a file in git and provide as pull requests? Or is this more complicated? :)

**Comment by petitlapin** [comment]
It's a bit more complicated, the translation repository is in subversion and in KDE repositories directly (no github mirror).
The repository is in https://websvn.kde.org/trunk/l10n-kf5/de/messages/extragear-edu/ and once you have done the fixes, either create a diff in https://phabricator.kde.org/differential/diff/create/ (but it would require a KDE account) or if you don't want, paste it somewhere, put the link here and I'll commit it in your name.

**Comment by petitlapin** [comment]
Hi,
This change has been fixed in https://phabricator.kde.org/R883:1511172
It will be available on next release, which we plan to do around beginning of March.

If you have more fixes on translation, don't hesitate to tell us using the easiest way for you.

Thank you!

Johnny
