### ISSUE TITLE
Translation under macOS

### ISSUE THREAD

**Issue by gjherbiet** [gcompris/GCompris-qt#232]
Hello,

I have sucessfully build Gcompris-qt under macOS, following the instructions from https://www.ynonperek.com/2017/09/18/building-gcompris-qt-on-macos/.

I now just have an issue with translation. After setting the language to French (`locale=fr_FR.UTF-8` in `~/Library/Preferences/gcompris/gcompris-qt.conf`) I have the following message while starting GCompris from Terminal:

```
$ Contents/MacOS/gcompris-qt
Unable to load translation for locale  "fr_FR" , use en_US by default
```

There also seem not to have `.po` files in the source tree.

How can I get the relevant translation for this application?

**Comment by petitlapin** [comment]
Hi,

to retrieve the latest translation files from KDE repo, you need to do "make getSvnTranslations". Then, to compile them: "make BuildTranslations".

Johnny

**Comment by gjherbiet** [comment]
Thanks, 

This is what I did on macOS to compile GCompris-qt with the translations using the homebrew package manager:

``` console
$ brew install qt cmake gettext
$ export Qt5_DIR="/usr/local/opt/qt/lib/cmake/Qt5/"
$ export PATH="$PATH:/usr/local/opt/qt/bin"
$ export PATH="/usr/local/opt/gettext/bin:$PATH"
$ git clone https://github.com/gcompris/GCompris-qt.git
$ cd GCompris-qt
$ mkdir build
$ cd build
$ make getSvnTranslations
$ cmake ..
$ make all
```
