### ISSUE TITLE
Add configuration options in smallnumbers activity

### ISSUE THREAD

**Issue by AkshayCHD** [gcompris/GCompris-qt#238]
Add options for different number representations like numbers, dots, romans etc on dices.
![image](https://user-images.githubusercontent.com/25455546/48182128-24daad80-e350-11e8-9d9d-5991d9af9407.png)
![image](https://user-images.githubusercontent.com/25455546/48182201-5f444a80-e350-11e8-9cee-cec0a1ae3adf.png)

**Comment by petitlapin** [comment]
Hi,

let's keep the improvements/issues in phabricator for the activities.

Thanks,

Johnny
