### ISSUE TITLE
FR - Disturbing sound of the letter "e"

### ISSUE THREAD

**Issue by lbartoletti** [gcompris/GCompris-qt#242]
The sound of the letter "e" in [French alphabet](https://raw.githubusercontent.com/gcompris/GCompris-data/master/voices/fr/alphabet/U0065.ogg) corresponds more to an "o" as "[rés**eau**](https://fr.wikipedia.org/wiki/Voyelle_mi-ferm%C3%A9e_post%C3%A9e_post%C3%A9rieure_arrondie)" than to an "e" as "[vo**eu**](https://fr.wikipedia.org/wiki/Voyelle_mi-ferm%C3%A9e_ant%C3%A9rieure_arrondie)"

**Comment by petitlapin** [comment]
Hi,
would taking the beginning of the 'é' or 'è' sound good enough for you? For us, the actual 'e' is good, maybe a bit short.
Corresponding sound are https://github.com/gcompris/GCompris-voices/blob/master/fr/alphabet/U00E9.ogg and https://github.com/gcompris/GCompris-voices/blob/master/fr/alphabet/U00E8.ogg

Which one do you prefer?

Johnny

**Comment by petitlapin** [comment]
I've updated it to https://github.com/gcompris/GCompris-data/blob/master/voices/fr/alphabet/U0065.ogg

We'll generate the voices packages soon to have it updated.

Thank you!

**Comment by lbartoletti** [comment]
Thanks :)
