### ISSUE TITLE
Build broken with cmake -G Ninja

### ISSUE THREAD

**Issue by eszlari** [gcompris/GCompris-qt#244]
```
[208/233] Performing configure step for 'qml_box2d'
Info: creating stash file /run/build/gcompris/_flatpak_build/qml_box2d-prefix/src/qml_box2d-build/.qmake.stash
[209/233] Performing build step for 'qml_box2d'
FAILED: qml_box2d-prefix/src/qml_box2d-stamp/qml_box2d-build 
cd /run/build/gcompris/_flatpak_build/qml_box2d-prefix/src/qml_box2d-build && /usr/bin/ninja && /usr/bin/cmake -E touch /run/build/gcompris/_flatpak_build/qml_box2d-prefix/src/qml_box2d-stamp/qml_box2d-build
ninja: error: loading 'build.ninja': No such file or directory
[211/233] Automatic MOC for target gcompris-qt
ninja: build stopped: subcommand failed.

```

**Comment by petitlapin** [comment]
hi,
we never tried to build it with ninja or support it.
You can try to disable box2D for now (cmake -DQML_BOX2D_MODULE=disabled) to see if it is better but I think it will not work when trying to compile the rcc files.
Box2d is built as an external project (https://github.com/gcompris/GCompris-qt/blob/master/cmake/box2d.cmake#L63) and only supports qmake (not cmake)

**Comment by petitlapin** [comment]
Should be fixed with https://cgit.kde.org/gcompris.git/commit/?id=212bb02d9725d99e3cf1f9605b40a194e2d8c411 (on master, it is not in any release yet).
As box2d only supports qmake as build system which does only generate makefiles, we still have to use `make` to compile this dependency.

**Comment by petitlapin** [comment]
I've just tested it and it now works fine.
