### ISSUE TITLE
Announcement about the full version becoming free

### ISSUE THREAD

**Issue by Wizard13** [gcompris/GCompris-qt#250]
Hi!
I'm curious about your announcement about the full version becoming free. The date in the Windows installers is still December 1st 2019 : https://gcompris.net/download/qt/windows/?C=M;O=D
I'm hesitant to re-download and test it. Maybe it's a stupid question, but is the announcement yours or were you... hacked? I just want to be sure that the installers are not compromised.

**Comment by petitlapin** [comment]
Hi,
I confirm the announce is official.
We changed the price on the Windows store but it's still in progress to be accepted.
I think we forgot to update the binaries in the website (so no need to download it, it will be the same for now), I'll keep you in touch when we have updated them.

**Comment by petitlapin** [comment]
After checking, it's the full version. Not sure why the date is still 1st December, we did a rsync and checked the md5 but the date didn't changed.
