### ISSUE TITLE
no sounds in Gnumch game

### ISSUE THREAD

**Issue by GodloveD** [gcompris/GCompris-qt#251]
I'm on Ubuntu 18.04 and have installed GCompris 0.81 based on QT 5.9.5 using `apt`.  The Gnumch game does not have any sounds, and in particular, the little green guy does not say "yummy yummy".

For comparison I've `apt install`-ed GCompris version 13.11 on Ubuntu 14.04.  In that version the Gnumch game has sounds, and the little green guy says "yummy yummy" every time he eats a number.  I believe this sound effect is driven by the file:
```
/usr/share/gcompris/boards/sounds/eat.wav
```
This file is not present in the newer version of GCompris, nor is the directory structure, so I have no idea where I would add it if it was missing.  I've also tried installing gstreamer good and bad plugin libraries (as well as brasero, just to make sure I have all of the gstreamer stuff).  That doesn't seem to help.  My kid really wants this sound effect.  What can I do? 

EDIT:
I should have added that other sounds seem to work just fine.  Sound is only missing in the Gnumch game.

**Comment by petitlapin** [comment]
Hi,

thank you for the report.

The resource files are directly compressed in a .rcc file, this is why you do not find it in the filesystem.

First of all, can you check if you have, in the configuration, the sound effects enabled?

For gstreamer, can you check if you have installed the 1.0 packages (I don't know exactly which one but it should be one of: gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly)?

If it does not work, can you confirm you have sound effects in "canal lock" activity?

Johnny

**Comment by petitlapin** [comment]
Forget last comment (I let it for information).
I just checked the code in 0.81 and effectively, we still had wav files playing disabled.
We don't have the hand to directly update the package on ubuntu but we provide latest versions as self-extractible packages:
https://gcompris.net/download/qt/linux/gcompris-qt-0.97-Linux32.sh (for 32 bits)
or
https://gcompris.net/download/qt/linux/gcompris-qt-0.97-Linux64.sh (for 64 bits)

it is a script where you specify the folder where to install GCompris, then you just have to run the bin/gcompris-qt.sh script.

**Comment by GodloveD** [comment]
purging the package manager install and installing from the script does the trick.  Thanks!  And thanks too for the very quick answer.

**Comment by petitlapin** [comment]
Great! Have fun
