### ISSUE TITLE
Windows installer doesn't create a shortcut in public desktop

### ISSUE THREAD

**Issue by Wizard13** [gcompris/GCompris-qt#256]
Windows installer doesn't create a desktop shortcut. Preferably, it should create one in public desktop for all users.

**Comment by petitlapin** [comment]
Hi,

thank you for the suggestion.

I just added it in commit: https://cgit.kde.org/gcompris.git/commit/?id=4102a064cce749bc676c2dd96f8d63bbe9d8b6cb

Johnny
