### ISSUE TITLE
Installation On  Android problem

### ISSUE THREAD

**Issue by anasoid** [gcompris/GCompris-qt#260]
I can't find Gcompris when searching on Google Play Store, and when i access directly using direct link i have the following message  "This item is not available in your country".

I m searching from Morocco

**Comment by petitlapin** [comment]
Hi,

as we are using openssl and crypto is forbidden for some countries, we had to disable it for Morocco.
You can still find the version in f-droid repository: https://f-droid.org/en/packages/net.gcompris.full/ or directly on our website: https://gcompris.net/download/qt/android/GCompris-Android-release-signed-aligned-armeabi-v7a-dl-0.97.3.apk

If you use the fdroid store, you will have notifications for the next updates but it won't be the case if you download the one from our website.

Sorry for the inconvenience,

Johnny

**Comment by anasoid** [comment]
Hi,

I already install application using APK, but it's not clear for me the relation openssl and crypto and my Country as there is no legislation in morocco related to using crypto and i don't think that Gcompris use sophisticate crypto like other security tools that are available for  my country.

I found it's abnormal to have this Open Source  complete educational application not for all the World, and having only 10K installation on play store. 

Thanks for your quick response.


![1600406282460](https://user-images.githubusercontent.com/10306838/93559906-b8cc2600-f978-11ea-8af3-7800c1cc9e41.JPEG)

**Comment by petitlapin** [comment]
@Animtim can you find the links you found about the use of openssl?

Regarding the version, until February, this one was paying and we had another version with less activities for free: https://play.google.com/store/apps/details?id=net.gcompris which had more than 100K downloads.
As we decided in February to provide the whole version for free on all platforms, we are "waiting" for users to switch to the full version.

**Comment by Animtim** [comment]
I could not find again the page I was referring to, but you can find similar info from:
https://www.openssl.org/ (legalities part)
https://www.gp-digital.org/world-map-of-encryption/
and http://www.cryptolaw.org/cls-sum.htm

The issue is that we have openssl libraries inside the package to be able to access https links. And so while we don't provide directly any crypto features inside the application, it appears that we would still require some declaration or authorization for some countries.

Note that we only have 13 countries for which the software is not available in the play store, so I don't think the number of install is very impacted by this.

**Comment by anasoid** [comment]
Thanks for your response,

I understand that blocking 13 countries will not impact total download, but may be total download is impact by demo version who still be downloaded by user (i still see new unsatisfying user's comments on demo version).

I understand that openssl can do more than it's used in application, but:

1. Openssl is present every where (linux, iot, ..) and can be download without any restriction.
2. If there is any problem with openssl why only blocking download on google play store and not direct download , i say that because most users will not be able to install it using apk or f-droid and specially with security alert regarding installation from unknown sources.
3. Application is present on linux repo and i can install it directly from package manager, why on android it will be different?

I hope that all this arguments will change your opinion on countries restriction.

**Comment by Animtim** [comment]
> I understand that blocking 13 countries will not impact total download, but may be total download is impact by demo version who still be downloaded by user (i still see new unsatisfying user's comments on demo version).

This yes, but as as @petitlapin said, we decided to give a transition time to inform users to switch to the full version. So we updated the demo to have a message when starting it, saying clearly that the full version is now free and that they should install it instead, and also added a similar note on the application description. We will remove the demo version for next release.

About your next comments, I might be wrong but I think the situation is a bit different when distributing from a store like this... I'll do more research about it, but I prefer not to change it before having more informed advices.

**Comment by anasoid** [comment]
Thanks @Animtim, @petitlapin 

Can'I knew how many time can take your research to have final decision ?

**Comment by Animtim** [comment]
That is not easy to tell (you never know how long it can take to find something when you start searching...).

**Comment by anasoid** [comment]
In case you can't release it for Morocco , and i want to release it on google play store  as fork  on my  responsibility there is any think that i should change in application (logo, name , ..) or not ?

**Comment by Animtim** [comment]
Well, please don't do that... As I see you are very insisting, I just made it available now, and hope it will be ok.

**Comment by anasoid** [comment]
Thanks, and sorry if I insist this is because the application is wonderful.
