### ISSUE TITLE
Can't download external assets on Fire OS 5

### ISSUE THREAD

**Issue by reddwarf69** [gcompris/GCompris-qt#261]
Using GCompris 0.97, the latest available on F-Droid, trying to download external assets results on "Download error (code: 99): TLS initialization failed".

I see https://www.gcompris.net/downloads-en.html says
```
WARNING: For Android version 4.4.2, it is recommended to directly download and install manually GCompris version 0.95 from our website, as the version 0.96 from the Play Store will not be able to download external assets with this Android version.
```
but it seems to be unrelated.
The system is using Fire OS 5.6.8.0, which according to https://developer.amazon.com/apps-and-games/fire-tablets is based on  Android 5.1 (API level 22).

By the way, is it not possible to publish it in the Amazon App Store?

**Comment by petitlapin** [comment]
Hi, thank you for reporting the issue.
I've created a new Merge Request to update to the version 1.0 in F-Droid (https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7745) with a more recent version of Qt and openSSL.
It may make sense to wait for this integration and test again with the 1.0?

You can also test with https://gcompris.net/download/qt/android/GCompris-Android-release-signed-aligned-armeabi-v7a-dl-1.0.apk but there won't be any notification when we will do updates (so better take it from F-Droid when updated there).

Regarding the Amazon Store, we don't plan to release it there. We consider publishing on the Play store is already covering most Android based devices. And for devices which do not have access to the Play store, users always have the possibility to install our apk directly, or to install it with F-Droid.

**Comment by RedDwarf69** [comment]
Thanks. About the Amazon Store, it's obviously up to you, but a couple of things to keep in mind:
- Given the cheap price of the tablets, and Amazon Kids+, the Amazon Fire tablets are likely popular with your target audience.
- GCompris **is** in the Amazon Store: https://www.amazon.co.uk/Bruno-Coudoin-GCompris-Educational-Software/dp/B00TKZNQL6. But it was last updated on 2015, it's version 0.50.
  * Lots of people are likely to find it and think it's the latest available, never knowing a newer version is in F-Droid.
  * Even if people go to the website, https://www.gcompris.net/downloads-en.html doesn't have any reference to https://gcompris.net/download/qt/android/GCompris-Android-release-signed-aligned-armeabi-v7a-dl-1.0.apk. So they are unlikely to find out they can download the latest APK directly from you.

**Comment by petitlapin** [comment]
It was put on the Amazon Store by the previous maintainer, but we don't want to maintain it anymore. We will ask bdoin to remove it from the Store as we won't update it anymore and, as you said, it is misleading to have an old unmaintained version here without telling users there is a more recent available.
Also, we will add to the website the link to the apk. It was not visible before as the application was sold on the Play Store. But, as it is now fully free, there is no reason to not give the direct link.
Thank you!

**Comment by petitlapin** [comment]
The latest version improved the support of older android for downloading assets. I'm closing this bug as it is old and we don't plan to add GCompris in the Amazon store. Feel free to open it again if needed.
