### ISSUE TITLE
Debian 11 XFCE - Screen flickering

### ISSUE THREAD

**Issue by cockadoolie** [gcompris/GCompris-qt#271]
I have installed GCompris for my kids on my Debian (from Debian repo - v 1.0.1), however when I launch it starts to behave strangely and begins the screen flicker when I move my mouse around the options.

2 of my Debian systems are affected (both stable, with xfce)

Has anyone got an idea what package, settings may I be missing? It may be connected to the QT setup of my system, but I am noob and unsure. I have a  video shot about the error, can mail it, if helps.

**Comment by petitlapin** [comment]
Closing it as running with `--software-renderer` fixes the issue
