### ISSUE TITLE
Checksum of downloaded file does not match

### ISSUE THREAD

**Issue by Gibbymint** [gcompris/GCompris-qt#283]
Hi 
I am using the latest version of Linux mint and downloaded gcompris. I am trying to update text images within the program but it fails to download because of an error. 
Download error (code 299) checksum of downloaded file does not match ....../.cache/KDE/gcompris-qt/data2/words/words.rcc 
I hope you can help, thanks

**Comment by petitlapin** [comment]
Hi thank you for the report and sorry for the inconvenience.

I can't reproduce it in an archlinux or ubuntu. Can you try to remove the ~/.cache/KDE/gcompris-qt folder and then start GCompris to check if the error is the same?

Which GCompris version are you using? Did you download it from package or from our website?

**Comment by Gibbymint** [comment]
Hello and thanks for the reply. I have the exact same problem on three machines all using the latest Linux Mint, I downloaded it from their software centre and it's version GCompris 2.3 Based on Qt 5.15.3

**Comment by petitlapin** [comment]
Thanks, I can reproduce after installing a Linux Mate. I'll dig deeper.

**Comment by petitlapin** [comment]
It should be better now, can you check please and close the bug if it is fixed for you?

**Comment by Gibbymint** [comment]
Sorry for not replying, couldn't get vpn working here in China. You fixed it, thanks for your support and a great script for kids.

**Comment by petitlapin** [comment]
No problem, great to hear it works now, have fun!

**Comment by noestreich** [comment]
i would like to reopen the issue. running into the same problem using the windows-installer and the version from the windows store, using the most recent version. 

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/7a8383d8-b6c6-4c2a-9d28-bfee8c31bb70" />
