### ISSUE TITLE
Click & drag is allowed in "Click and draw", "Draw numbers" and "Number sequence"

### ISSUE THREAD

**Issue by spacevoyager78** [gcompris/GCompris-qt#297]
Hi!
In "Click and draw", "Draw numbers" and "Number sequence" activities, one could click on the first number/circle and drag the pointer on the rest of the numbers/circles in sequence to quickly complete the activities. I'm not sure that's the intended behavior, since the instructions state that you have to click the numbers/circles.

**Comment by petitlapin** [comment]
Hi,
thanks for the report! It's not a bug for these activities. Timothée clarified the manual in https://invent.kde.org/education/gcompris/-/commit/1b03afdf6e6b0b45e59437c4fdd0ff48a955f85b so the instructions reflect on that.

It will be available on the next release (we plan to do it second half of January).

Thanks again!
